server:
  port: ${SERVER_PORT:8080}
  ssl:
    key-store: classpath:certs/keystore.p12
    key-store-password: ${PRIVATE_KEY_PASSWORD:123456}
    key-store-type: PKCS12
    key-alias: alias


spring:
  datasource:
    url: ${DATABASE_URL:jdbc:sqlserver://localhost:1433;databaseName=bxmd;encrypt=true;trustServerCertificate=true;characterEncoding=UTF-8;}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:MyPass@word}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
  #    database-platform: org.hibernate.dialect.SQLServerDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
#  ssl:
#    bundle:
#      pem:
#        server:
#          keystore:
#            certificate: classpath:certs/server.crt
#            private-key: classpath:certs/server.key
#            private-key-password: ${PRIVATE_KEY_PASSWORD:123456}
#          reload-on-update: true
#          truststore:
#            certificate: client/certs/client.crt

apiBasePath: /api/v1

security:
  jwt:
    auth:
      header: Authorization
      prefix: Bearer
    access-token-expiration-milliseconds: ${ACCESS_TOKEN_EXPIRED:36000}
    refresh-token-expiration-milliseconds: ${REFRESH_TOKEN_EXPIRED:2592000}
    secret: ${SECRET_KEY:I6oWsZeW1Kc9cCqIxgcPzQbsffv9Q5afA1ID+XoyIdFdF+Xar+NwqahS4+w5fgqL+meIwSOmMypUlSJEGEUJqA==}

feature-flag:
  init-user: false
  init-data: false
