POST https://localhost:8080/api/v1/receipt/search
Content-Type: application/json

{
  "searchCriteria": {
    "orderNumber": "",
    "receiptCode": "",
    "senderName": "",
    "senderIdCard": "",
    "senderPhone": "",
    "receiverName": "",
    "receiverIdCard": "",
    "receiverPhone": "",
    "billStatus": ["CREATED"],
    "settlementStatus": ["CANCELED", "IN_PROGRESS"]
  },
  "page": 0,
  "pageSize": 5,
  "direction": "",
  "sortBy": ""
}

###
GET https://localhost:8080/api/v1/receipt/11

### get production
GET https://27.71.229.40:8082/api/v1/receipt/1

###
DELETE https://localhost:8080/api/v1/receipt/7

### create receipt
POST https://localhost:8080/api/v1/receipt
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOIiwiZXhwIjoxNzIyNjAxNTE1fQ.ePTk0YQH9wh2P0OJs9qLuvnqHB0MylUsz4PPLU55CqNPoejNWXLLVzRjVwZVBa6f_W0M_FUzlYLnTvwNIZ0iYg
Content-Type: application/json

{
  "orderNumber": "{{$uuid}}",
  "receiptCode": "{{$uuid}}",
  "senderName": "senderName",
  "senderIdCard": "senderIdCard",
  "senderPhone": "senderPhone",
  "senderAddress": "senderAddress",
  "receiverName": "receiverName",
  "receiverIdCard": "receiverIdCard",
  "receiverPhone": "receiverPhone",
  "receiverProvince": {
    "id": 8
  },
  "receiverDistrict": {
    "id": 8
  },
  "receiverCommune": {
    "id": 8
  },
  "receiverAddress": "receiverAddress",
  "itemName": "itemName",
  "itemValue": "0",
  "itemLength": "1",
  "itemWidth": "2",
  "itemHeight": "3",
  "itemWeight": "4",
  "itemFragile": true,
  "itemQuantity": 1,
  "serviceFee": "123.3",
  "packagingServices": [
    {
      "quantity": 1,
      "isReused": false,
      "packagingPrice": {
        "id": 1,
        "code": "code",
        "name":"name",
        "label": "label",
        "size":"size"
      }
    },
    {
      "quantity": 2,
      "isReused": false,
      "packagingPrice": {
        "id": 2,
        "code": "code",
        "name":"name",
        "label": "label",
        "size":"size"
      }
    }
  ],
  "packagingServiceFee": "133.3",
  "packagingServiceQuantity": 1,
  "totalAmount": "50",
  "subPackages": [
    {
      "detail": "sub package detail 1",
      "note": "sub package note 1"
    },
    {
      "detail": "sub package detail 2",
      "note": "sub package note 1"
    }
  ],
  "billStatus": "CREATED",
  "settlementStatus": "PENDING"
}

###
PUT https://localhost:8080/api/v1/receipt
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOIiwiZXhwIjoxNzIyNjAxNTE1fQ.ePTk0YQH9wh2P0OJs9qLuvnqHB0MylUsz4PPLU55CqNPoejNWXLLVzRjVwZVBa6f_W0M_FUzlYLnTvwNIZ0iYg
Content-Type: application/json

{
  "id": 1,
  "orderNumber": "{{$uuid}}",
  "receiptCode": "{{$uuid}}",
  "senderName": "vuong",
  "senderIdCard": "senderIdCard updated",
  "senderPhone": "senderPhone updated",
  "senderAddress": "senderAddress updated",
  "receiverName": "test",
  "receiverIdCard": "receiverIdCard updated",
  "receiverPhone": "receiverPhone updated",
  "receiverProvince": {
    "id": 9
  },
  "receiverDistrict": {
    "id": 9
  },
  "receiverCommune": {
    "id": 9
  },
  "receiverAddress": "receiverAddress",
  "itemName": "itemName",
  "itemValue": "0",
  "itemLength": "1",
  "itemWidth": "2",
  "itemHeight": "3",
  "itemWeight": "4",
  "itemFragile": true,
  "itemQuantity": 1,
  "serviceFee": "123.3",
  "packagingServices": [
    {
      "quantity": 7,
      "isReused": false,
      "packagingPrice": {
        "id": 1,
        "code": "code",
        "name":"name",
        "label": "label",
        "size":"size"
      }
    },
    {
      "quantity": 7,
      "isReused": false,
      "packagingPrice": {
        "id": 2,
        "code": "code",
        "name":"name",
        "label": "label",
        "size":"size"
      }
    }
  ],
  "packagingServiceFee": "133.3",
  "packagingServiceQuantity": 1,
  "totalAmount": "50"
}

###
# curl --location --request PUT 'https://localhost:8080/api/v1/receipt'
#--header 'Content-Type: application/json'
#--header 'Accept: */*'
#--header 'Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOIiwiZXhwIjoxNzIyNjAxNTE1fQ.ePTk0YQH9wh2P0OJs9qLuvnqHB0MylUsz4PPLU55CqNPoejNWXLLVzRjVwZVBa6f_W0M_FUzlYLnTvwNIZ0iYg'
#--data '{
#        "id": 1,
#        "senderName": "updated",
#        "senderIdCard": "senderIdCard",
#        "senderPhone": "senderPhone",
#        "senderAddress": "senderAddress",
#        "receiverName": "receiverName",
#        "receiverIdCard": "receiverIdCard",
#        "receiverPhone": "receiverPhone",
#        "receiverProvince": {
#            "id": 2,
#            "code": "",
#            "name": "An Giang 2",
#            "km": null,
#            "licensePlateCode": null,
#            "routeCode": null,
#            "regionFreightPrice": null
#        },
#        "receiverDistrict": {
#            "id": 2,
#            "code": "",
#            "name": "An Phú"
#        },
#        "receiverCommune": {
#            "id": 2,
#            "code": "",
#            "name": "An Phú",
#            "label": "An GiangAn Phú",
#            "km": "25",
#            "shipmentType": "Nội Tuyến",
#            "percentRate": "100"
#        },
#        "receiverAddress": "receiverAddress",
#        "itemName": "itemName",
#        "itemValue": 0.00,
#        "itemLength": 1.00,
#        "itemWidth": 2.00,
#        "itemHeight": 3.00,
#        "itemWeight": 4.00,
#        "itemFragile": true,
#        "itemQuantity": 1,
#        "serviceFee": 123.30,
#        "packagingService": "packagingService",
#        "packagingServiceFee": 133.30,
#        "packagingServiceQuantity": 1,
#        "totalAmount": 50.00
#    }'
PUT https://localhost:8080/api/v1/receipt
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOIiwiZXhwIjoxNzIyNjAxNTE1fQ.ePTk0YQH9wh2P0OJs9qLuvnqHB0MylUsz4PPLU55CqNPoejNWXLLVzRjVwZVBa6f_W0M_FUzlYLnTvwNIZ0iYg
Content-Type: application/json

{
  "id": 1,
  "senderName": "updated 2",
  "senderIdCard": "senderIdCard 3",
  "senderPhone": "senderPhone",
  "senderAddress": "senderAddress",
  "receiverName": "receiverName",
  "receiverIdCard": "receiverIdCard",
  "receiverPhone": "receiverPhone",
  "receiverProvince": {
    "id": 6
  },
  "receiverDistrict": {
    "id": 6
  },
  "receiverCommune": {
    "id": 6
  },
  "receiverAddress": "receiverAddress",
  "itemName": "itemName",
  "itemValue": 0.00,
  "itemLength": 1.00,
  "itemWidth": 2.00,
  "itemHeight": 3.00,
  "itemWeight": 4.00,
  "itemFragile": true,
  "itemQuantity": 1,
  "serviceFee": 123.30,
  "packagingService": "packagingService",
  "packagingServiceFee": 133.30,
  "packagingServiceQuantity": 1,
  "totalAmount": 50.00
}

###
DELETE https://localhost:8080/api/v1/receipt/1

